---

default_language_version:
  python: python3.6
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
          - --keep-runtime-typing
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.0.0"
    hooks:
      - id: django-upgrade
        args: ["--target-version", "3.1"]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-tidy-imports
          - flake8-print
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.4.1
    hooks:
      - id: check-github-workflows
        require_serial: true
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: '/tests/'
        args:
          - --recursive
          - --skip=B101,B608,B308,B703,B106

exclude: |
  (?x)(
    /(
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.pytest_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
    | migrations
    | docs
  )
