# Generated by Django 3.1.7 on 2021-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "REGULAR"), (1, "MEDIUM")], default=0
            ),
        )
    ]
