# Generated by Django 3.1.7 on 2021-07-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0003_author")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="external_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
