# Generated by Django 3.1.7 on 2021-07-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("news", "0004_article_external_url")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_featured",
            field=models.BooleanField(default=False),
        )
    ]
