# Generated by Django 3.1.13 on 2022-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_pin_external_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="external_text",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
