# Generated by Django 3.1.13 on 2022-10-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_pin_external_text_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="date_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="date_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
