# Generated by Django 2.2.10 on 2020-11-04 21:03

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("page", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="page", name="in_menu", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="page",
            name="picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True, null=True, upload_to="page/page/", verbose_name="Image"
            ),
        ),
    ]
