# Generated by Django 2.2.10 on 2020-11-06 20:08

from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("page", "0002_content")]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "picture",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="page/picture/", verbose_name="Image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
