# Generated by Django 3.1.14 on 2022-05-12 14:30

from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "picture",
                    versatileimagefield.fields.VersatileImageField(
                        upload_to="link/picture", verbose_name="Image"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="The number determines the order with which the links will be shown.",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
