UNIVERSITIES = [
    "Blekinge Institute of Technology",
    "Chalmers University of Technology",
    "Dalarna University",
    "Ersta Sköndal Bräcke University College",
    "GIH – the Swedish School of Sport and Health Sciences",
    "Halmstad University",
    "Jönköping University",
    "KMH – Royal College of Music in Stockholm",
    "Karlstad University",
    "Karolinska Institutet",
    "Konstfack",
    "KTH Royal Institute of Technology",
    "Kristianstad University",
    "Linköping University",
    "Linnaeus University",
    "Luleå University of Technology",
    "Lund University",
    "Malmö University",
    "Mid Sweden University",
    "Mälardalen University",
    "Royal Institute of Art",
    "SLU – Swedish University of Agricultural Sciences",
    "SMI – University College of Music Education in Stockholm",
    "Sophiahemmet University College",
    "Stockholm School of Economics",
    "Stockholm School of Theology",
    "Stockholm University",
    "Stockholm University of the Arts",
    "Swedish Defence University",
    "Södertörn University",
    "The Swedish Red Cross University College",
    "Umeå University",
    "University West",
    "University of Borås",
    "University of Gothenburg",
    "University of Gävle",
    "University of Skövde",
    "Uppsala University",
    "Örebro University",
    "― Other university within EU/EEC ―",
    "― Other university outside EU/EEC ―",
]

PROGRAMMES = [
    "Aerospace Engineering",
    "Applied and Computational Mathematics",
    "Architectural Lighting Design",
    "Architecture",
    "Chemical Engineering for Energy and Environment",
    "Civil and Architectural Engineering",
    "Communication Systems",
    "Computer Science",
    "Computer Simulations for Science and Engineering",
    "Decentralized Smart Energy Systems",
    "Electric Power Engineering",
    "Electromagnetics, Fusion and Space Engineering",
    "Embedded Systems",
    "Energy for Smart Cities",
    "Engineering Design",
    "Engineering Materials Science",
    "Engineering Mechanics",
    "Engineering Physics",
    "Entrepreneurship and Innovation Management​​",
    "Environmental Engineering and Sustainable Infrastructure",
    "Environomical Pathways for Sustainable Energy Systems",
    "ICT Innovation",
    "Industrial Management",
    "Industrial and Environmental Biotechnology",
    "Information and Communication Technology",
    "Information and Network Engineering",
    "Innovative Sustainable Energy Engineering",
    "Integrated Product Design",
    "Interactive Media Technology",
    "Machine Learning",
    "Macromolecular Materials",
    "Management and Engineering of Environment and Energy",
    "Mathematics",
    "Media Management",
    "Medical Biotechnology",
    "Medical Engineering",
    "Molecular Science and Engineering",
    "Molecular Techniques in Life Science",
    "Nanotechnology",
    "Naval Architecture",
    "Nuclear Energy",
    "Nuclear Energy Engineering",
    "Polymer Technology",
    "Production Engineering and Management",
    "Railway Engineering",
    "Real Estate and Construction Management",
    "Renewable Energy",
    "Security and Cloud Computing",
    "Smart Electrical Networks and Systems",
    "Software Engineering of Distributed Systems",
    "Sports Technology",
    "Sustainable Energy Engineering",
    "Sustainable Production Development",
    "Sustainable Technology",
    "Sustainable Urban Planning and Design",
    "Systems, Control and Robotics",
    "Technology, Work and Health",
    "Transport and Geoinformation Technology",
    "Transport, Mobility and Innovation",
    "Turbomachinery Aeromechanical University Training",
    "Vehicle Engineering",
]

STATISTICS_YEAR_START = 2018
STATISTICS_PROGRAMME_MIN_PERCENTAGE = 2
STATISTICS_PROGRAMME_OTHER_LABEL = "Other"
