# Generated by Django 2.2.4 on 2020-02-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        )
    ]
