# Generated by Django 2.2.4 on 2020-02-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0002_event_description_remove_limit")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="code",
            field=models.CharField(blank=True, max_length=255, unique=True),
        )
    ]
