# Generated by Django 2.2.10 on 2020-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='attendance_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
