# Generated by Django 2.2.10 on 2020-04-10 11:57

from django.db import migrations, models
import event.enums


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GENERAL'), (2, 'LECTURE'), (3, 'LUNCH'), (4, 'EXTERNAL'), (5, 'WEBINAR'), (6, 'OTHER')], default=event.enums.EventType(1)),
        ),
    ]
