# Generated by Django 2.2.10 on 2020-04-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0007_event_location")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="account_required",
            field=models.BooleanField(default=False),
        )
    ]
