# Generated by Django 2.2.10 on 2020-04-14 20:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_registration_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starts_at',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='event.Event')),
            ],
        ),
    ]
