# Generated by Django 2.2.10 on 2020-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_available',
            field=models.BooleanField(default=True),
        ),
    ]
