# Generated by Django 2.2.10 on 2020-05-05 18:40

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='preview',
            field=versatileimagefield.fields.VersatileImageField(default='', upload_to='event/attachment/preview/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
