# Generated by Django 2.2.10 on 2020-08-23 11:08

from django.db import migrations, models
import django.db.models.deletion
import event.enums


class Migration(migrations.Migration):

    dependencies = [("event", "0016_attachment_type")]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "GENERAL"),
                            (1, "CEREMONY"),
                            (2, "TALK"),
                            (3, "TEAM_BUILDING"),
                            (4, "MEAL"),
                            (5, "DEMO"),
                            (6, "EVENT_START"),
                            (7, "EVENT_END"),
                        ],
                        default=event.enums.ScheduleType(0),
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="event.Session",
                    ),
                ),
            ],
        )
    ]
