# Generated by Django 2.2.10 on 2020-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0017_schedule")]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="place",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
