# Generated by Django 2.2.10 on 2020-08-23 13:51

from django.db import migrations, models
import event.enums


class Migration(migrations.Migration):

    dependencies = [("event", "0018_schedule_place")]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "GENERAL"),
                    (1, "CEREMONY"),
                    (2, "TALK"),
                    (3, "TEAM_BUILDING"),
                    (4, "MEAL"),
                    (5, "DEMO"),
                    (6, "EVENT_START"),
                    (7, "EVENT_END"),
                    (8, "GAME"),
                    (9, "PRIZE"),
                ],
                default=event.enums.ScheduleType(0),
            ),
        )
    ]
