# Generated by Django 2.2.18 on 2021-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_event_social_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='social_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
