# Generated by Django 3.1.7 on 2021-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_event_social_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
