# Generated by Django 3.1.7 on 2021-05-10 15:06

import app.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0022_session_google_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="First name")),
                ("surname", models.CharField(max_length=255, verbose_name="Last name")),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "picture",
                    versatileimagefield.fields.VersatileImageField(
                        default="event/speaker/picture/profile.png",
                        storage=app.storage.OverwriteStorage(),
                        upload_to="event/speaker/picture/",
                        verbose_name="Image",
                    ),
                ),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="speakers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
