# Generated by Django 3.1.7 on 2021-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0024_speakerrole")]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="description",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speaker",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
