# Generated by Django 3.1.7 on 2021-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0025_speaker_info")]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="scholar_url",
            field=models.URLField(blank=True, null=True),
        )
    ]
