# Generated by Django 3.1.13 on 2021-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0026_speaker_scholar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="diet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="diet_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
