# Generated by Django 3.1.13 on 2021-10-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0027_event_diet"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="has_food",
            field=models.BooleanField(default=False),
        ),
    ]
