# Generated by Django 3.1.13 on 2021-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0028_event_has_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="collect_resume",
            field=models.BooleanField(default=False),
        ),
    ]
