# Generated by Django 3.1.13 on 2021-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_event_collect_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slack_ts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
