# Generated by Django 3.1.13 on 2022-03-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0030_event_slack_ts"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="signup_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
