# Generated by Django 3.1.13 on 2022-12-06 10:57

import app.storage
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0032_event_social_picture_overwite"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="social_picture_sq",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                storage=app.storage.OverwriteStorage(),
                upload_to="event/social/squared/",
                verbose_name="Social image (squared)",
            ),
        ),
    ]
