# Generated by Django 3.1.13 on 2023-05-17 13:53

import app.storage
from django.db import migrations, models
import event.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0033_event_social_picture_sq"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poster",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                storage=app.storage.OverwriteStorage(),
                upload_to="event/poster/",
                verbose_name="Poster",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Room, venue(*), city(*), country(*)",
                max_length=255,
                null=True,
                validators=[event.validators.validate_location],
            ),
        ),
    ]
