# Generated by Django 2.2.13 on 2021-03-13 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlackChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_general", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                ("topic", models.CharField(blank=True, max_length=255, null=True)),
                ("purpose", models.CharField(blank=True, max_length=255, null=True)),
                ("num_members", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255)),
                ("external_creator_id", models.CharField(max_length=255)),
                ("external_created_at", models.DateTimeField(auto_now_add=True)),
            ],
        )
    ]
