# Generated by Django 3.1.13 on 2021-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_slacklog_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slacklog",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "ARTICLE"), (2, "EVENT"), (3, "WARNING"), (4, "JOB")],
                default=1,
            ),
        ),
    ]
