# Generated by Django 3.1.13 on 2022-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_slackuser_picture_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='external_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
