# Generated by Django 3.1.13 on 2022-05-05 15:41

import app.storage
from django.db import migrations
import messaging.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_slackuser_external_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, storage=app.storage.OverwriteStorage(), upload_to=messaging.models.slack_user_picture_filename, verbose_name='Slack image'),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='picture_original',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, storage=app.storage.OverwriteStorage(), upload_to=messaging.models.slack_user_picture_original_filename, verbose_name='Slack original image'),
        ),
    ]
