# Generated by Django 3.1.7 on 2021-04-14 19:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("business", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "INTERNSHIP"),
                            (1, "SUMMER_INTERNSHIP"),
                            (2, "PART_TIME"),
                            (3, "FULL_TIME"),
                            (4, "VOLUNTEER"),
                            (5, "OTHER"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="business.company",
                    ),
                ),
            ],
        )
    ]
