# Generated by Django 2.2.4 on 2020-03-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last name"
            ),
        )
    ]
