# Generated by Django 2.2.10 on 2020-03-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0003_user_registration_finished")]

    operations = [
        migrations.CreateModel(
            name="GoogleUser",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("user.user",),
        )
    ]
