# Generated by Django 2.2.10 on 2020-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="other_university",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
