# Generated by Django 2.2.13 on 2021-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0010_role")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slack_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
