# Generated by Django 2.2.13 on 2021-03-13 22:30

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("user", "0011_user_slack_id")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slack_display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="slack_picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="user/slack/picture/",
                verbose_name="Slack image",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="slack_status_emoji",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="slack_status_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
