# Generated by Django 2.2.13 on 2021-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0014_user_slack_auth")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slack_picture_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
