# Generated by Django 2.2.18 on 2021-03-28 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("user", "0015_user_slack_picture_hash")]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(max_length=5000)),
                ("time", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "histories"},
        )
    ]
