# Generated by Django 3.1.7 on 2021-04-22 20:32

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(default='user/role/picture/profile.png', upload_to='user/role/picture/', verbose_name='Image'),
        ),
    ]
