# Generated by Django 3.1.7 on 2021-04-19 10:35

import app.storage
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("user", "0018_role_picture")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=versatileimagefield.fields.VersatileImageField(
                default="user/picture/profile.png",
                storage=app.storage.OverwriteStorage(),
                upload_to="user/picture/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="slack_picture",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                storage=app.storage.OverwriteStorage(),
                upload_to="user/slack/picture/",
                verbose_name="Slack image",
            ),
        ),
    ]
