# Generated by Django 3.1.7 on 2021-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0019_user_picture_storage")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_author",
            field=models.BooleanField(default=False),
        )
    ]
