# Generated by Django 3.1.7 on 2021-07-23 19:08

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [("user", "0020_user_is_author")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="orcid",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[user.models.validate_orcid],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="scholar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "ORGANISER"), (1, "PARTICIPANT"), (2, "SPONSOR")],
                default=1,
            ),
        ),
    ]
