# Generated by Django 3.1.7 on 2021-07-23 19:59

from django.db import migrations, models


def update_divisions(apps, schema_editor):
    Division = apps.get_model("user.Division")

    divisions = []
    for division in Division.objects.all():
        division.display_name = division.name
        divisions.append(division)

    Division.objects.bulk_update(divisions, fields=("display_name",))


class Migration(migrations.Migration):

    dependencies = [("user", "0021_user_social_networks")]

    operations = [
        migrations.AddField(
            model_name="division",
            name="display_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(update_divisions, migrations.RunPython.noop),
    ]
