# Generated by Django 3.1.7 on 2021-07-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0022_division_display_name")]

    operations = [
        migrations.AlterField(
            model_name="division",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
