# Generated by Django 3.1.7 on 2021-07-23 21:06

from django.db import migrations, models


def update_teams(apps, schema_editor):
    Team = apps.get_model("user.Team")

    teams = []
    for team in Team.objects.all():
        team.code = str(team.starts_at.year)
        teams.append(team)

    Team.objects.bulk_update(teams, fields=("code",))


class Migration(migrations.Migration):

    dependencies = [("user", "0023_division_display_name_blank")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(update_teams, migrations.RunPython.noop),
    ]
