# Generated by Django 3.1.7 on 2021-07-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0025_team_code_blank")]

    operations = [
        migrations.AlterModelOptions(
            name="division", options={"ordering": ["display_name"]}
        ),
        migrations.AlterModelOptions(name="role", options={"ordering": ["user"]}),
    ]
