# Generated by Django 3.1.7 on 2021-07-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0026_user_meta_order")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="researchgate_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
