# Generated by Django 3.1.13 on 2021-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_user_diet"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_forgotten",
            field=models.BooleanField(default=False),
        ),
    ]
