# Generated by Django 3.1.13 on 2022-05-05 15:55

import app.storage
from django.db import migrations, models
import user.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_user_remove_slack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(default='user/picture/profile.png', storage=app.storage.OverwriteStorage(), upload_to=user.models.user_picture_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=app.storage.OverwriteStorage(), upload_to=user.models.user_resume_filename),
        ),
    ]
