name: Create and publish a Docker image
on:
  push:
    branches: [ beta, master ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup production or beta
        shell: bash
        run: echo "##[set-output name=branch;]$( [ "master" == ${GITHUB_REF#refs/heads/} ] && echo "latest" || echo "beta" )"
        id: extract_branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: website:${{ steps.extract_branch.outputs.branch }}
